import os
import sys
import time
print("Human, you have entered the GlaDos AI, I am here to help you, you currently are facing towards a circular companion cube, you will need to cut the corners down on this companion cube to place it in the lava vatt, I will help you, I know you believe the cake is a lie, but is the companion cube also a lie? Please type 'start()' to start my systems!")

def intro():
    print("Human, you have entered the GlaDos AI, I am here to help you, you currently are facing towards a circular companion cube, you will need to cut the corners down on this companion cube to place it in the lava vatt, I will help you, I know you believe the cake is a lie, but is the companion cube also a lie? Please type 'start()' to start my systems!")




def start():
    diameter = float (input("what is the diameter? "))
    arcA = float (input("whats the arc angle? "))
    radius = diameter /2
    area = radius * (radius * 3.14)
    circum = diameter * 3.14
    arcL = circum * (arcA / 360)
    print("Your radius is", radius)
    print("Your area is", area)
    print("Your circumfrence is", circum)
    print("Your arc length is", arcL)
    print("Thank you for operating with GlaDos")
    print("You definitely. Wont. Regret. It. ;)")

          
    print("With this information, will you now insert the perfectly cut companion cube?")
    yes=input("WILL YOU???? ")
    if yes == ("yes"):
        print("You fool, the companion cube was a lie")
        time.sleep(2)
        print("=================================================")
        print("DEPLOYING THE DEADLY NEUROTOXIN")
        print("=================================================")
        time.sleep(1)
        print("GlaDos thanks you for your help in assassinating yourself")
        print("Terminating the Operation and the human")
        os.execl(sys.executable, sys.executable, *sys.argv)
    elif yes == ("no"):
        time.sleep(1)
        print("You.... HOW.... HOW DID YOU KNOW..... I... ")
        time.sleep(1)
        print("================================================")
        print("GlaDos.exe has stopped responding.")
        print("================================================")
        time.sleep(0.5)
        print("owadioaiofshf H sjklsjhlsgdjhklfg;sjkldfjhklsdghsjhksgdjhklgdsjhklsd")
        time.sleep(2)
        print("sjklerkljwejhk E sfgdjhkfgdsfja;gjkljklrioerhthdh;lsfdjhklsrgjhklwtejhklsgdjhr")
        time.sleep(2)
        print("wda;fjlejlgdjhk L fgdfghfsdghsfdsfjld;kldfgjkjklcmvxm,.b.xgdsgsjkfjkds;jks;fjkla")
        time.sleep(2)
        print("awklsjldejfdjksf P kudgfjhfgjkfdjhkfdgdgdgfjkldvnxcm,bnvcjkbjfjkjkxcnjbcjfbjcjnv")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("jjkljklajhkfsdfgj M lssjkjksnjkvnjksjklfjsjflsfshfsfsfzjvxcvzb,vcx,.;.lfkdgwdajkdfd")
        time.sleep(2)
        print("whfefjksdjlnxvcnxvb E nxxvnmnvnbfbdfnjkdbgjhkvjhkbbsdsgsfhajkldsajklfsflnndjvjdnjvnjs")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("")
        time.sleep(2)
        print("             .,-:;//;:=,")
        time.sleep(1)
        print("         . :H@@@MM@M#H/.,+%;,")
        time.sleep(1)
        print("      ,/X+ +M@@M@MM%=,-%HMMM@X/,")
        time.sleep(1)
        print("     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-")
        time.sleep(1)
        print("    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.")
        time.sleep(1)
        print("  ,%MM@@MH ,@%=            .---=-=:=,.")
        time.sleep(1)
        print("  -@#@@@MX .,              -%HX$$%%%+;")
        time.sleep(1)
        print(" =-./@M@M$                  .;@MMMM@MM:")
        time.sleep(1)
        print(" X@/ -$MM/                    .+MM@@@M$")
        time.sleep(1)
        print(",@M@H: :@:                    . -X#@@@@-")
        time.sleep(1)
        print(",@@@MMX, .                    /H- ;@M@M=")
        time.sleep(1)
        print(".H@@@@M@+,                    %MM+..%#$.")
        time.sleep(1)
        print(" /MMMM@MMH/.                  XM@MH; -;")
        time.sleep(1)
        print("  /%+%$XHH@$=              , .H@@@@MX,")
        time.sleep(1)
        print("   .=--------.           -%H.,@@@@@MX,")
        time.sleep(1)
        print("   .%MM@@@HHHXX$$$%+- .:$MMX -M@@MM%.")
        time.sleep(1)
        print("     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=")
        time.sleep(1)
        print("       =%@M@M#@$-.=$@MM@@@M; %M%=")
        time.sleep(1)
        print("        ,:+$+-,/H#MMMMMMM@- -,")
        time.sleep(1)
        print("               =++%%%%+/:-.")
        time.sleep(1)

        os.execl(sys.executable, sys.executable, *sys.argv)

def portallogo():
    print("             .,-:;//;:=,")
    print("         . :H@@@MM@M#H/.,+%;,")
    print("      ,/X+ +M@@M@MM%=,-%HMMM@X/,")
    print("     -+@MM; $M@@MH+-,;XMMMM@MMMM@+-")
    print("    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.")
    print("  ,%MM@@MH ,@%=            .---=-=:=,.")
    print("  -@#@@@MX .,              -%HX$$%%%+;")
    print(" =-./@M@M$                  .;@MMMM@MM:")
    print(" X@/ -$MM/                    .+MM@@@M$")
    print(",@M@H: :@:                    . -X#@@@@-")
    print(",@@@MMX, .                    /H- ;@M@M=")
    print(".H@@@@M@+,                    %MM+..%#$.")
    print(" /MMMM@MMH/.                  XM@MH; -;")
    print("  /%+%$XHH@$=              , .H@@@@MX,")
    print("   .=--------.           -%H.,@@@@@MX,")
    print("   .%MM@@@HHHXX$$$%+- .:$MMX -M@@MM%.")
    print("     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=")
    print("       =%@M@M#@$-.=$@MM@@@M; %M%=")
    print("        ,:+$+-,/H#MMMMMMM@- -,")
    print("               =++%%%%+/:-.")


