import time
# 12 Days Of Christmas - A PAINFUL SONG! / 2:39PM - 12/2/19
# Lyrics from MetroLyrics.com

Day1=str("On the first day of christmas my true love sent to me")
Day2=str("On the second day of christmas my true love sent to me")
Day3=str("On the third day of christmas my true love sent to me")
Day4=str("On the fourth day of christmas my true love sent to me")
Day5=str("On the fifth day of christmas my true love sent to me")
Day6=str("On the sixth day of christmas my true love sent to me")
Day7=str("On the seventh day of christmas my true love sent to me")
Day8=str("On the eights day of christmas my true love sent to me")
Day9=str("On the ninth day of christmas my true love sent to me")
Day10=str("On the tenth day of christmas my true love sent to me")
Day11=str("On the eleventh day of christmas my true love sent to me")
Day12=str("On the twelth day of christmas my true love sent to me")
E1=str("A Partridge In A Pear Tree.")
E2=str("Two Turtle Doves And ")
E3=str("Three French Hens, ")
E4=str("Four Calling Birds, ")
E5=str("Five Golden Rings, ")
E6=str("Six Geese a Laying, ")
E7=str("Seven Swans a Swimming, ")
E8=str("Eight Maids a Milking, ")
E9=str("Nine Ladies Dancing, ")
E10=str("Ten Lords a Leaping, ")
E11=str("Eleven Pipers Piping, ")
E12=str("Twelve Drummers Drumming.")
print(Day1, E1)
time.sleep(2)
print("")
print(Day2, E2, E1)
time.sleep(3)
print("")
print(Day3, E3, E2, E1)
time.sleep(3)
print("")
print(Day4, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day5, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day6, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day7, E7, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day8, E8, E7, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day9, E9, E8, E7, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day10, E10, E9, E8, E7, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day11, E11, E10, E9, E8, E7, E6, E5, E4, E3, E2, E1)
time.sleep(3)
print("")
print(Day12, E12, E11, E10, E9, E8, E7, E6, E5, E4, E3, E2, E1)

